-- AlterTable
ALTER TABLE "ingredients" ALTER COLUMN "calories_per_100" SET NOT NULL,
ALTER COLUMN "calories_per_100" SET DEFAULT 0,
ALTER COLUMN "carbs_per_100" SET NOT NULL,
ALTER COLUMN "carbs_per_100" SET DEFAULT 0,
ALTER COLUMN "fat_per_100" SET NOT NULL,
ALTER COLUMN "fat_per_100" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "recipes" ALTER COLUMN "amount" SET NOT NULL,
ALTER COLUMN "amount" SET DEFAULT 0,
ALTER COLUMN "calories" SET NOT NULL,
ALTER COLUMN "calories" SET DEFAULT 0,
ALTER COLUMN "carbs" SET NOT NULL,
ALTER COLUMN "carbs" SET DEFAULT 0,
ALTER COLUMN "fat" SET NOT NULL,
ALTER COLUMN "fat" SET DEFAULT 0;
