export const TEXTS = {
  app: {
    title: 'Diéta Napló',
    loading: 'Diéta Napló betöltése...',
  },
  auth: {
    signIn: 'Bejelentkezés Google-lel',
    signingIn: 'Bejelentkezés...',
    signInFailed: 'Sikertelen bejelentkezés',
  },
  common: {
    add: 'Új',
    cancel: 'Mégse',
    save: 'Mentés',
    saving: 'Mentés...',
    update: 'Módosítás',
    name: 'Név',
    actions: 'Műveletek',
    noMatches: 'Nincs találat.',
  },
  nav: {
    ingredients: 'Alapanyagok',
    recipes: 'Receptek',
    meals: 'Étkezések',
  },
  nutrients: {
    calories: 'Kalória',
    cal: 'Kal',
    carbs: 'Szénhidrát',
    ch: 'CH',
    fat: 'Zsír',
    kcalUnit: 'kCal',
    chUnit: 'CH',
    fatUnit: 'zsír',
  },
  ingredients: {
    search: 'Alapanyag keresése...',
    newIngredient: 'Új Alapanyag',
    calPer100g: 'Kal / 100g',
    carbsPer100g: 'CH / 100g',
    fatPer100g: 'Zsír / 100g',
    vegetable: 'Zöldség',
    carbLimit: 'CH limit',
    noIngredients: 'Még nincsenek alapanyagok. Add hozzá az elsőt!',
    loadError: 'Alapanyagok betöltése sikertelen',
    noFound: 'Nincs ilyen alapanyag',
  },
  recipes: {
    search: 'Recept keresése...',
    newPlaceholder: 'Új recept neve...',
    newRecipe: 'Új Recept',
    notFound: 'Recept nem található',
    backToRecipes: 'Vissza a receptekhez',
    ingredients: 'Alapanyagok',
    ingredient: 'Alapanyag',
    amountG: 'Mennyiség (g)',
    servings: 'Adag',
    addIngredient: 'Alapanyag hozzáadása...',
    noIngredients: 'Még nincsenek alapanyagok. Adj hozzá egyet fent.',
    noRecipes: 'Még nincsenek receptek. Hozd létre az elsőt!',
    loadError: 'Receptek betöltése sikertelen',
    g: 'g',
    variant: 'Variáns',
    basedOn: 'Alap',
  },
  meals: {
    newDay: 'Új Nap',
    addMeal: 'Étkezés hozzáadása',
    dish: 'Étel',
    amount: 'Mennyiség',
    addDish: 'Étel hozzáadása...',
    noMeals: 'Még nincsenek étkezések. Adj hozzá egyet fent.',
    noDays: 'Még nincsenek napok. Hozd létre az elsőt!',
    dayNotFound: 'Nap nem található',
    backToMeals: 'Vissza az étkezésekhez',
    loadError: 'Napok betöltése sikertelen',
    g: 'g',
    customize: 'Testreszabás',
  },
  dishes: {
    ingredient: 'alapanyag',
    recipe: 'recept',
  },
  mealTypes: {
    morningSnack: 'Előreggeli',
    breakfast: 'Reggeli',
    brunch: 'Tízórai',
    lunch: 'Ebéd',
    afternoonSnack: 'Uzsonna',
    dinner: 'Vacsora',
    lateNightSnack: 'Utóvacsora',
  },
  shoppingList: {
    ingredient: 'Alapanyag',
    amountG: 'Mennyiség (g)',
    copyList: 'Lista másolása',
    copied: 'Másolva!',
    noData: 'Nincs bevásárolnivaló ebben az időszakban.',
    itemCount: 'tétel',
    daysCount: 'Napok',
  },
  copyDay: {
    title: 'Nap másolása',
    copy: 'Másolás',
    dateExists: 'Ez a nap már létezik',
  },
  confirm: {
    deleteIngredient: 'Alapanyag törlése',
    deleteRecipe: 'Recept törlése',
    usedInRecipes: 'Receptekben használva',
    usedInDays: 'Napokban használva',
    confirmDelete: 'Törlés',
  },
};
