export const TEXTS = {
  app: {
    title: 'Diéta Napló',
    loading: 'Diéta Napló betöltése...',
  },
  auth: {
    signIn: 'Bejelentkezés Google-lel',
    signingIn: 'Bejelentkezés...',
    signInFailed: 'Sikertelen bejelentkezés',
  },
  common: {
    add: 'Új',
    cancel: 'Mégse',
    save: 'Mentés',
    saving: 'Mentés...',
    update: 'Módosítás',
    name: 'Név',
    actions: 'Műveletek',
    noMatches: 'Nincs találat.',
  },
  nav: {
    dashboard: 'Áttekintés',
    ingredients: 'Alapanyagok',
    recipes: 'Receptek',
    meals: 'Étkezések',
  },
  nutrients: {
    calories: 'Kalória',
    cal: 'Kal',
    carbs: 'Szénhidrát',
    ch: 'CH',
    fat: 'Zsír',
  },
  ingredients: {
    search: 'Alapanyag keresése...',
    newIngredient: 'Új Alapanyag',
    calPer100g: 'Kal / 100g',
    carbsPer100g: 'CH / 100g',
    fatPer100g: 'Zsír / 100g',
    vegetable: 'Zöldség',
    carbLimit: 'CH limit',
    noIngredients: 'Még nincsenek alapanyagok. Add hozzá az elsőt!',
    loadError: 'Alapanyagok betöltése sikertelen',
    noFound: 'Nincs ilyen alapanyag',
  },
  recipes: {
    search: 'Recept keresése...',
    newPlaceholder: 'Új recept neve...',
    newRecipe: 'Új Recept',
    notFound: 'Recept nem található',
    backToRecipes: 'Vissza a receptekhez',
    ingredients: 'Alapanyagok',
    ingredient: 'Alapanyag',
    amountG: 'Mennyiség (g)',
    servings: 'Adag',
    addIngredient: 'Alapanyag hozzáadása...',
    noIngredients: 'Még nincsenek alapanyagok. Adj hozzá egyet fent.',
    noRecipes: 'Még nincsenek receptek. Hozd létre az elsőt!',
    nIngredients: (n: number): string => `${n} alapanyag`,
    loadError: 'Receptek betöltése sikertelen',
    g: 'g',
  },
  meals: {
    newDay: 'Új Nap',
    addMeal: 'Étkezés hozzáadása',
    dish: 'Étel',
    amount: 'Mennyiség',
    addDish: 'Étel hozzáadása...',
    noMeals: 'Még nincsenek étkezések. Adj hozzá egyet fent.',
    noDays: 'Még nincsenek napok. Hozd létre az elsőt!',
    dayNotFound: 'Nap nem található',
    backToMeals: 'Vissza az étkezésekhez',
    loadError: 'Napok betöltése sikertelen',
    g: 'g',
  },
  mealTypes: {
    morningSnack: 'Előreggeli',
    breakfast: 'Reggeli',
    brunch: 'Tízórai',
    lunch: 'Ebéd',
    afternoonSnack: 'Uzsonna',
    dinner: 'Vacsora',
    lateNightSnack: 'Utóvacsora',
  },
  dashboard: {
    from: 'Ettől',
    to: 'Eddig',
    totalCalories: 'Összes Kalória',
    totalCarbs: 'Összes CH',
    totalFat: 'Összes Zsír',
    days: 'Napok',
    perDay: '/nap',
    gPerDay: 'g/nap',
    dailyStats: 'Napi statisztika',
    ingredientsTab: 'Alapanyagok',
    shoppingList: 'Bevásárlólista',
    date: 'Dátum',
    mealsCount: 'Étkezések',
    dishesCount: 'Ételek',
    carbsG: 'CH (g)',
    fatG: 'Zsír (g)',
    noData: 'Nincs adat ebben az időszakban.',
  },
  ingredientAgg: {
    ingredient: 'Alapanyag',
    totalG: 'Összes (g)',
    usedIn: 'Felhasználva',
    total: 'Összesen',
    nDishes: (n: number): string => `${n} étel`,
    noData: 'Nem használtál alapanyagot ebben az időszakban.',
  },
  shoppingList: {
    ingredient: 'Alapanyag',
    amountG: 'Mennyiség (g)',
    copyList: 'Lista másolása',
    copied: 'Másolva!',
    noData: 'Nincs bevásárolnivaló ebben az időszakban.',
  },
};
